### ISSUE TITLE
array key 'charges' is not defined (Stripe)

### ISSUE THREAD

**Issue by SebastianUhlig** [stephenjude/laravel-payment-gateways#10]
Hi! I started to work with the Stripe API yesterday and wanted to take the opportunity to use this package.

However, I noticed an error when paying for an order.
As soon as I am redirected back, I get the error message:
`"Undefined array key "charges"" // app/Http/Controllers/Shop/PaymentController.php:18`

After some debugging I noticed that there is no 'charges' inside the $provider in the confirmPayment function of the StripeProvider.
Does it have to be like this? Did I make a mistake or is it possibly an update on Stripe's part?

![confirmPayment code](https://user-images.githubusercontent.com/25252089/235344245-36789c1a-7e59-41eb-9b26-298a99b682db.png)

![provider dump](https://user-images.githubusercontent.com/25252089/235344346-1fc6da5e-3b5e-43f2-b6a3-4334aaef8506.png)

**Comment by stephenjude** [comment]
From the payload returned looks like we don't have any trace of the customer email returned from Stripe?
