### ISSUE TITLE
can't seem to get it working with paystack

### ISSUE THREAD

**Issue by iamkarsoft** [stephenjude/laravel-payment-gateways#2]
```

            $provider = PaymentGateway::make('paystack');

            $session = $provider->initializePayment([$this->payment_data['currency'],$this->payment_data['amount'],$this->customer_contact,$this->payment_data]);

            $session->checkoutUrl; // Returns checkout link.

            $session->sessionReference; // Returns session reference.
```
![Screenshot 2022-08-21 at 10 44 06 AM](https://user-images.githubusercontent.com/5146869/185792101-a8214f38-61c0-4c5a-9d76-de05218218f6.png)
![Screenshot 2022-08-21 at 10 37 40 AM](https://user-images.githubusercontent.com/5146869/185792105-67267b83-1be6-4e03-b3f8-db84b8ec5604.png)

![Screenshot 2022-08-21 at 10 36 49 AM](https://user-images.githubusercontent.com/5146869/185792116-6ee69fae-dc7b-4da5-8148-5d2b5ec8b387.png)

**Comment by stephenjude** [comment]
Hi this package is in heavy development even though that’s what we use in production. I haven’t had time to update the docs. 

Please exercise patience. I will do that this week.

**Comment by iamkarsoft** [comment]
Sure. Hopefully soon. Thanks for the great work.

**Comment by iamkarsoft** [comment]
@stephenjude any timeline on updating the docs?

**Comment by stephenjude** [comment]
Yeah before the end of the week.

**Comment by stephenjude** [comment]
The documentation is ready now.

**Comment by iamkarsoft** [comment]
> The documentation is ready now.

thanks so much.
